name: PeacefulSpawn
main: brexmania123\PeacefulSpawn\Main
version: 1.1
api:
 - 3.0.0-ALPHA11
load: POSTWORLD
author: "brexmania123"
website: "https://github.com/brexmania123/PeacefulSpawn"
commands:
  ps:
    description: Toggles PeacefulSpawn's protection
    usage: "/ps"
    permission: peacefulspawn.toggle
permissions:
  peacefulspawn:
    description: "Allows access to all PeacefulSpawn features."
    default: op
    children:
      peacefulspawn.toggle:
        description: "Allows the user to toggle spawn protection."
        default: op
